// backend/src/controllers/authControllers.js
const axios = require('axios');

const loginUser = async (req, res, next) => {
    try {
        const { username, password, ssoToken } = req.body;

        // 1. Check if this is an Enterprise SSO attempt
        if (ssoToken) {
            return res.status(200).json({
                success: true,
                message: "SSO Authentication successful. GOC Engineer Session active.",
                token: ssoToken,
                user: username || "SSO User",
                expires: Date.now() + 8 * 60 * 60 * 1000 
            });
        }

        // 2. Basic validation check for standard credentials
        if (!username || !password) {
            return res.status(400).json({
                success: false,
                message: "Credentials or SSO Session details are required."
            });
        }

        // 3. Local Sandbox Fallback (Keep this so you can still test offline!)
        if (username === 'admin' && password === 'goc123') {
            return res.status(200).json({
                success: true,
                message: "Sandbox Authentication successful. Local GOC Developer Session active.",
                token: "mock-corporate-secure-jwt-token-xyz789",
                user: username,
                expires: Date.now() + 2 * 60 * 60 * 1000 
            });
        }

        // 🚀 4. PRODUCTION LIVE WIRE: Authenticate directly against real Centreon API
        try {
            const CENTREON_BASE_URL = process.env.CENTREON_API_URL || 'https://your-centreon-domain.com/centreon/api/v2';
            
            // Forward work credentials to Centreon's authentication endpoint
            const response = await axios.post(`${CENTREON_BASE_URL}/login`, {
                security: {
                    credentials: {
                        login: username,
                        password: password
                    }
                }
            });

            // Extract the real secure token generated by your Centreon instance
            const realCentreonToken = response.data?.security?.token;

            if (!realCentreonToken) {
                return res.status(401).json({
                    success: false,
                    message: "Authentication server did not return a valid session token."
                });
            }

            // Success! Return the real token to React
            return res.status(200).json({
                success: true,
                message: "GOC Live Authentication successful.",
                token: realCentreonToken, // React will save this real token in localStorage
                user: username,
                expires: Date.now() + 2 * 60 * 60 * 1000 // Match token lifespan (e.g., 2 hours)
            });

        } catch (centreonApiError) {
            console.error("Centreon Authentication Rejected:", centreonApiError.response?.data || centreonApiError.message);
            
            return res.status(401).json({
                success: false,
                message: "Invalid work credentials or unauthorized corporate access."
            });
        }

    } catch (error) {
        next(error); 
    }
};

module.exports = {
    loginUser
};